version: '3'

services:
  pgsql:
    image: postgres:13
    container_name: databases_pgsql
    ports:
      - '${PGSQL_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${PGSQL_PASSWORD:-secret}'
      POSTGRES_DB: '${PGSQL_DATABASE}'
      POSTGRES_USER: '${PGSQL_USERNAME}'
      POSTGRES_PASSWORD: '${PGSQL_PASSWORD:-secret}'
    volumes:
      - './pgsql/data:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${PGSQL_DATABASE}", "-U", "${PGSQL_USERNAME}" ]
      retries: 3
      timeout: 5s
    networks:
      - databases
  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: databases_mysql
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USERNAME}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - './mysql/data:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}" ]
      retries: 3
      timeout: 5s
    networks:
      - databases
networks:
  databases:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
